worker_processes 1;
pid nginx.pid;
error_log nginx-error.log warn;
events { worker_connections 256; }
http {
    access_log off;
    server_tokens off;
    client_body_temp_path client_temp;
    proxy_temp_path proxy_temp;
    fastcgi_temp_path fastcgi_temp;
    uwsgi_temp_path uwsgi_temp;
    scgi_temp_path scgi_temp;
    client_max_body_size 32k;
    server {
        listen 8080;
        server_name _;
        location / {
            proxy_pass http://127.0.0.1:3000;
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header Connection "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto https;
            proxy_connect_timeout 5s;
            proxy_read_timeout 30s;
            proxy_redirect off;
        }
    }
    server {
        listen 8081;
        server_name _;
        client_max_body_size 128k;
        location / {
            proxy_pass http://127.0.0.1:3001;
            proxy_http_version 1.1;
            proxy_set_header Host $http_host;
            proxy_set_header Connection "";
            proxy_connect_timeout 5s;
            proxy_read_timeout 35s;
            proxy_redirect off;
        }
    }

}
